### ISSUE TITLE
RFE: set_trace() on receipt of SIGTRAP

### ISSUE THREAD

**Issue by rbarlow** [tamentis/rpdb#15]
It would be very nice if users could interrupt a running process by sending SIGTRAP to it and get a pdb shell wherever the process happened to be. This would allow applications to ship with rpdb always listening for this signal, which would be very nice for debugging (or even live fixing!).

For explictness, a new API could be introduced so that the user can specify whether they want this signal handler setup or not. Perhaps something like this as a companion to rpdb.set_trace():

```
import rpdb


rpdb.handle_trap()
```

I suggested SIGTRAP because of its description in man 7 signal:

```
Signal       Value     Action   Comment
…
SIGTRAP        5        Core    Trace/breakpoint trap
```

**Comment by rbarlow** [comment]
@seandst said he'd have this on your desk by Monday. Have a good weekend!

**Comment by tamentis** [comment]
It does sound like an awesome idea.

**Comment by seandst** [comment]
I jumped the gun a little.
