### ISSUE TITLE
Request: January release

### ISSUE THREAD

**Issue by rbarlow** [tamentis/rpdb#17]
Hello! Would you be willing to make a release in January? I'd love to be able to include the signal handler feature from @seandst's pull request a few weeks ago in Fedora 24, which branches from Fedora's development branch on February 2. If you can make a release sometime in January (preferably not Jan 31 so I have some time to package ☺) I will be able to get it included in the next Fedora release.

Thanks again for this very useful tool!

**Comment by tamentis** [comment]
Absolutely, I will do that today!

**Comment by rbarlow** [comment]
Thank you @tamentis! I've already released it in Rawhide, and will add an update for Fedora 23 as well. rpdb FTW!

https://apps.fedoraproject.org/packages/python-rpdb
